### ISSUE TITLE
Error on fetch_object() in results

### ISSUE THREAD

**Issue by dnichols178** [cahyadsn/disc#1]
Receive the following error in results.php 

`PHP Fatal error:  Call to a member function fetch_object() on a non-object in ../../../../result.php on line 100 `

PHP Version: 5.3
MySQL Version: 5.6.32
Apache

**Comment by cahyadsn** [comment]
code fixing on line 100 when $result is empty

-- data will be updated soon

**Comment by dnichols178** [comment]
Same error on line 119

**Comment by cahyadsn** [comment]
already fixing
