### ISSUE TITLE
demo disc

### ISSUE THREAD

**Issue by amir-sheikhzadeh** [cahyadsn/disc#3]
Hi, I saw the source you shared on GitHub. Thank you for sharing. But this source is very different from the demo version .could you send me demo version source code that I found it in this address.
https://psycho.cahyadsn.com/disc/
thanks in advance

**Comment by Andi210996** [comment]
untuk aplikasi utuhnya gimana mas.?

**Comment by cahyadsn** [comment]
I can't provide the real data as on demo in this github repo since the data for demo version is proprietary. Please contact me via email for more information, thx.

**Comment by Andi210996** [comment]
how to get the full apk
