### ISSUE TITLE
Inquiry about your DISC Tool

### ISSUE THREAD

**Issue by jana-msys** [cahyadsn/disc#4]
My name is Jananan, I am a php developer and I was trying to use your code for a DISC tool. (https://github.com/cahyadsn/disc).  I was able to find that there was a rectification because of interchanging names in the backend file.

I also wanted to understand how I can get the results as shown in the demo website after completing the test. https://psycho.cahyadsn.com/disc/.

Can you connect with  me on my mail id jananan1992@gmail.com or whatsapp me on +918438416259

**Comment by cahyadsn** [comment]
hi Jananan, since the DiSC real data is proprietary that I can't put it on my github repo. You can read **DiSC Classic Paper Profile - DiSC® 2800 Series Personal Profile System®** (https://www.discprofile.com/products/disc-classic/) for more detail how to interpreted the result test.

**Comment by jana-msys** [comment]
Hi, 

Can you share the mobile no? I would like to connect with you or can you ping me on my whatsapp. +918438416259

Regards,
Jananan
